version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: alexeagle/ngcontainer  
    steps:
      - checkout
      
      - run: node --version
      - run: npm --version
      - run: java -version
      - run: google-chrome --version
      - run: yarn --version

      - run: npm install
      
      # TESTS!
      - run: xvfb-run -a npm run e2e test-8-1.conf.js
      - run: xvfb-run -a npm run e2e test-8-2.conf.js
      - run: xvfb-run -a npm run e2e test-8-3.conf.js
